### ISSUE TITLE
Cannot read property 'length' of undefined.

### ISSUE THREAD

**Issue by tickletehpickle** [megalon/after-dark-bot#4]
I'm using the TTT-game branch as it was newer, but even if I use the master branch. The same issue still persists.

`root@tis-is-not-a-bot:/opt/after-dark-bot# node index.js
+++++++++++++ Ready! +++++++++++++
----------------anonMembers----------------
[]
/opt/after-dark-bot/modules/messagehandler.js:27
        if(pathToSaveFiles[pathToSaveFiles.length - 1] !== filePathSlash){
                                           ^

TypeError: Cannot read property 'length' of undefined
    at Array.methods.init (/opt/after-dark-bot/modules/messagehandler.js:27:44)
    at Array.methods.init (/opt/after-dark-bot/modules/anonymizer.js:89:17)
    at Client.client.on (/opt/after-dark-bot/index.js:23:16)
    at emitNone (events.js:111:20)
    at Client.emit (events.js:208:7)
    at WebSocketConnection.triggerReady (/opt/after-dark-bot/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:125:17)
    at WebSocketConnection.checkIfReady (/opt/after-dark-bot/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:141:61)
    at GuildCreateHandler.handle (/opt/after-dark-bot/node_modules/discord.js/src/client/websocket/packets/handlers/GuildCreate.js:13:31)
    at WebSocketPacketManager.handle (/opt/after-dark-bot/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:103:65)
    at WebSocketConnection.onPacket (/opt/after-dark-bot/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:333:35)
`

**Comment by dj3hac** [comment]
Exact same issue as above.

**Comment by randomguuy12** [comment]
Same issue
